services:
  ros2_env:
    container_name: ros2_env
    build: ./Dockerfile_ros_arm
    image: ros2_env/raspi
    network_mode: host
    volumes:
      - ./src:/home/ros2_workspace
    command: tail -F anything