# version: '3.8'
services:
  ros_tcp_endpoint:
    container_name: ros_tcp_endpoint
    build: ./Dockerfile_ros_vanilla
    ports:
      - 10000:10000
    volumes:
      - ./src:/home/ros2_workspace
      - /dev/shm:/dev/shm
    command: >
      /bin/bash -c
      "source /home/ros2_workspace/install/setup.bash &&
      ros2 run ros_tcp_endpoint default_server_endpoint --ros-args -p ROS_IP:=0.0.0.0"
  
  foxglove_bridge:
    container_name: foxglove_bridge
    build: ./Dockerfile_ros_vanilla
    volumes:
      - ./src:/home/ros2_workspace
      - /dev/shm:/dev/shm
    ports:
      - 9090:9090
    command: >
      /bin/bash -c
      "source /home/ros2_workspace/install/setup.bash &&
      ros2 launch rosbridge_server rosbridge_websocket_launch.xml"

  ros2_tf:
    container_name: ros2_tf
    build: ./Dockerfile_ros_tf
    network_mode: host
    pid: host
    volumes:
      - ./src:/home/ros2_workspace
      - /dev/shm:/dev/shm
    command: /bin/bash -c "tail -F anything"