services:
  ros_env:
    build: ./Dockerfile_ros_arm
    image: ros2/arm_env:humble
    container_name: ros_env
    network_mode: host
    privileged: true
    devices:
      - /dev/gpiomem
    volumes:
      - ./src:/ros2_workspace
    command: tail -F anything
