tracker_node:
  ros__parameters:
    sample_rate: 10.0
    delta_max: 20.0
    num_probation_updates: 10
    max_update_pause: 6000.0 
    estimatation_uncertainty: [100.,100.,100.,100.,0.01,0.01]
    measurment_uncertainty: [2.,2.]
    processnoise: [.5, .5, 0.6, 0.6, 0.05, 0.05]

visualizer_node:
  ros__parameters:
    delta_max: 20.0
    publish_visualization: false
    draw_visualization: true

object_detector_node:
  ros__parameters:
    confidence_limit: 0.8
