# assigns a travel plan to a tracked vehicle

string plan_name    # name of the travel plan
uint8 tracker_id      # tracking id of the vehicle
string ipadress     # ip address of the tinycar
---
int8 status  # 0=travel plan assigned; 1=not assigned, vehicle not found; 2=not assigned, plan not found